### ISSUE TITLE
Create Expected Assertions for Requests

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#11]
A assertions.yaml with some assertions for each request.

for example, `posts_list_all` must have:
* x Length?
* this Structure?
* which type of data for each field?

Tasks:
- [ ] define a format for it
- [ ] implement how to run the assertions

in the future, we can create alerts when the assertions fails

**Comment by camilamaia** [comment]
Format Suggestion:
```yaml
api:
  base_url: ${BASE_URL}
  requests:
    - name: health # health
      method: get
      path: /health
      asserts:
        - name: Body returns OK
          value: ${{ response["health"].json() == "OK" }}
        - name: Content-Type is application/json
          value: ${{ response["health"].header[" content-type"] == "application/json" }}
```

How to do that?

Run, for each request node, assertions and generate a `test result` object for it.
After all, we can generate a jUnit report, or similar, passing thorough each test result.
