### ISSUE TITLE
Implement Cases

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#13]
```yaml
...
          requests:
                  - name: list_all # posts_list_all
                    method: get
                    case: when user is not authenticated
                    ...
                  - name: list_all # posts_list_all
                    method: get
                    case: when user is authenticated
                    ...
```
