### ISSUE TITLE
Remove `api` key

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#209]
Remove `api` key from the specification. I don't see any purpose in having it right now. If we want to add some extra metadata, we can do the same way OpenAPI does, with extra sections: https://swagger.io/docs/specification/basic-structure/ Our `endpoints` would be the same as `paths` for OpenAPI.

Change from this:

```yaml
api:
  endpoints:
    - name: sample-api
      path: http://api.example.com/v1
      requests:
        - name: users
          path: /users
          method: get
```

to this:

```yaml
endpoints:
  - name: sample-api
    path: http://api.example.com/v1
    requests:
      - name: users
        path: /users
        method: get
```

Besides we also need to:
- Update documentation at [scanapi/website](https://github.com/scanapi/website/tree/master/_docs_v1) 
- Update examples at [scanapi/examples](https://github.com/scanapi/examples)
