### ISSUE TITLE
Add support for hiding selected request body

### ISSUE THREAD

**Issue by malminhas** [scanapi/scanapi#235]
I would like to hide the body in the generated report for just ONE of the requests in the sequence which is called `get_token`.  Is there a way to do that?   Currently if I do this in the .scanapi.yaml configuration file:
```
report:
  hide-request:
    headers:
      - Authorization
    body:
      - get_token
```
I get the following in the output on running the scanapi CLI:
`a bytes-like object is required, not 'str'`
