### ISSUE TITLE
.scanapi.yaml not formatting report.html

### ISSUE THREAD

**Issue by Vimai** [scanapi/scanapi#253]
hi,

i am trying format my report.

currently using ```scanapi    1.0.5```

my .scanapi.yaml

```
project_name: local-project
output_path: my-local-report.html
report:
  hide_request:
    headers:
      - client_id
      - access_token
```

but only the output_path works.

i'm running like:
```scanapi scanapi.yaml ```

the ```scanapi run scanapi.yaml``` command does not work for me

and i have to use de 'api' key(s) at 'root' scope in scanapi.yaml

full code -> [https://github.com/Vimai/examples/tree/master/local-example-api](https://github.com/Vimai/examples/tree/master/local-example-api)

**Comment by camilamaia** [comment]
@Vimai Hi! We are about to create a 2.0.0 release, that is why it might be confusing. You can check the examples and the code for the previous version 1.0.5.

- Examples: https://github.com/scanapi/scanapi/tree/v1.0.5
- Doc and repo: https://github.com/scanapi/examples/tree/v1.0.5

For you example, it should work like this:

```yaml
project-name: local-project
output_path: my-local-report.html
report:
  hide-request:
    headers:
      - client_id
      - access_token
```

For the next version, we will have only `_` instead of a mix of underscore and dash.
