### ISSUE TITLE
New feature: retry request calls

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#298]
## Retry request calls

The possibility to retry certain call if a connection error happened.

**Comment by flaviotruzzi** [comment]
Can I work on this?

I was thinking on adding a `retry` block under the `endpoints` like this:

```yaml
endpoints:
  - name: pokeapi
    path: https://pokeapi.co/api/v2/
    endpoints:
      - name: pokemon
        path: pokemon
        requests:
          - name: list_all
            method: get
            retry:
              assert: ${{ response.status_code == 429 }}
              max_wait: 5
              max_retries: 2      
            vars:
              pokemon_name: ${{ response.json()["results"][0]["name"] }}
            tests:
              - name: status_code_is_200
                assert: ${{ response.status_code == 200 }}            
              - name: response_time_is_under_half_second
                assert: ${{ response.elapsed.total_seconds() < 0.5 }}
              - name: results_length_is_20
                assert: ${{ len(response.json()["results"]) == 20 }}
              - name: count_is_gte_1050
                assert: ${{ response.json()["count"] >= 1050 }}
          - name: details
            method: get
            path: ${pokemon_name}
``` 

assertion would be the condition for retry, using exponential backoff, adding maximum number of retries and max time to wait. Maybe we could survive with just max time to wait, what do you think?
