### ISSUE TITLE
Hide tokens and authorization info in the generated report

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#31]
## Description

Add the possibility to hide tokens and authorization info in the generated report to avoid expose sensitive information via [configuration file](https://github.com/scanapi/scanapi/blob/124983ca0365e4552f7ad56a6f9523a829c6c293/scanapi/settings.py#L5) (usually `.scanapi.yaml`).

Change the sensitive information value to `<sensitive_information>`

Configuration Options:
- `report`
-- `hide-response` or `hide-request`
--- `headers` or `body` or `url`
---- list of keys to hide

Example:
```yaml
report:
  hide-response:
    headers:
      - Authorization
      - api-key
  hide-response:
    body:
      - api-key
```

The logic is implemented inside the [hide_sensitive_info method](https://github.com/scanapi/scanapi/blob/124983ca0365e4552f7ad56a6f9523a829c6c293/scanapi/utils.py#L25)

Example of how this should be rendered in the reports:

![image](https://user-images.githubusercontent.com/2728804/83572730-73d2cf80-a500-11ea-9307-549b9915596d.png)

- [x] header for request
- [x] header for response
- [x] body for request
- [x] body for response
- [ ] url for request
- [ ] url for response
