### ISSUE TITLE
Fix `hide_response` `body`

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#370]
## Description

```shell
Error to make request `http://demo.scanapi.dev/health/`.
'Response' object has no attribute 'body'
```

We need to check if http_message has body attribute before accessing it: https://github.com/scanapi/scanapi/blob/master/scanapi/hide_utils.py#L66

request.body exists, but response.body doesn't. For response we need to use response.text or response.content

## Reproducing the error

Spec File:
```yaml
# scanapi.yaml

endpoints:
  - name: snippets-api
    path: ${BASE_URL}
    headers:
      Content-Type: application/json
    requests:
      - name: health
        method: get
        path: /health/
        tests:
          - name: status_code_is_200
            assert: ${{ response.status_code == 200 }}
          - name: bode_equals_ok
            assert: ${{ response.json() == "OK!" }}
      - name: get_token
        path: /api-token-auth/
        method: post
        body:
            username: ${USER}
            password: ${PASSWORD}
        vars:
          token: ${{response.json()["token"]}}
        tests:
          - name: status_code_is_200
            assert: ${{ response.status_code == 200 }}
```

Configuration File
```yaml
# scanapi.conf
project_name: Snippets API
report:
  hide_response:
    body:
      - token
```

```shell
$ scanapi run
Loading file ./scanapi.conf
Loading file scanapi.yaml
Writing documentation
Making request GET http://demo.scanapi.dev/health/

Error to make request `http://demo.scanapi.dev/health/`.
'Response' object has no attribute 'body'
...
```

![image](https://user-images.githubusercontent.com/2728804/118543526-bcdc5d80-b72a-11eb-8cba-2dd04694c3ec.png)
