### ISSUE TITLE
Hide response content sensitive info

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#371]
## Description

Hide response content sensitive info. 

Since body does not exist for responses objects (see [this](https://github.com/scanapi/scanapi/issues/370) for more details), we need a config to hide content fields for a response

```yaml
report:
  hide-response:
    headers:
      - Authorization
    content:
      - token
```
