### ISSUE TITLE
Error making request when request has no body and there is a `report::hide_request::body` configuration.

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#392]
### Environment
- Operating System: Mac OS
- ScanAPI version: 2.3.0

### Description of the bug 
Error making request when request has no body and there is a `report::hide_request::body` configuration.

```shell
▶ scanapi run
Loading file ./scanapi.conf
Loading file scanapi.yaml
Writing documentation
Making request GET http://demo.scanapi.dev/api/v1/health/

Error to make request `http://demo.scanapi.dev/api/v1/health/`.
the JSON object must be str, bytes or bytearray, not 'NoneType'

Making request POST http://demo.scanapi.dev/api/v1/rest-auth/login/

The documentation was generated successfully.
It is available at /Users/camilamaia/workspace/scanapi-org/test-tutorial/scanapi-report.html
```

![image](https://user-images.githubusercontent.com/2728804/121076386-bc286b80-c7ac-11eb-9918-908ed4660abc.png)

### Expected behavior ?
Health request to appear in the report

### How to reproduce the the bug ?
specification file `scanapi.yaml`:

```yaml
endpoints:
  - name: snippets-api
    path: http://demo.scanapi.dev/api/v1/
    headers:
      Content-Type: application/json
    requests:
      - name: health
        method: get
        path: /health/
        tests:
          - name: status_code_is_200
            assert: ${{ response.status_code == 200 }}
          - name: body_equals_ok
            assert: ${{ response.json() == "OK!" }}
      - name: get_token
        path: /rest-auth/login/
        method: post
        body:
          username: ${USER}
          password: ${PASSWORD}
```

Configuration file `scanapi.conf`:

```yaml
report:
  hide_request:
    body:
      - password
  hide_response:
    body:
      - key
```
