### ISSUE TITLE
Custom variable not being evaluated when defined in the same request

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#508]
### Environment
ScanAPI version: 2.6.0

### Description of the bug 

When the custom var is defined and used in the same request, it is not being evaluated.
 
### How to reproduce the bug ?

```yml
endpoints:
  - name: snippets-api
    path: http://demo.scanapi.dev/api/v1/
    headers:
      Content-Type: application/json
    requests:
      - name: health
        vars:
          my_var: "one"
        path: health/?${my_var}
```

![image](https://user-images.githubusercontent.com/2728804/133853630-f4a30a49-d832-4da4-81eb-65e0e4c5813a.png)

### Expected behavior?

![image](https://user-images.githubusercontent.com/2728804/133853877-7ea80d85-9a4d-43b8-8159-b20002799e21.png)

### Anything else we need to know?

It works for env variables. The problem appears only for custom vars

**Comment by leonardomaier** [comment]
@camilamaia @Pradhvan I'm currently working on this, could you assign it to me please?

**Comment by Pradhvan** [comment]
Done! Thanks for picking this up @leonardomaier 😄

**Comment by leonardomaier** [comment]
@Pradhvan I have some questions about some specific cases, for example, let's suppose that we've set up a YAML file like this:

```yaml
endpoints:
  - name: snippets-api
    path: http://demo.scanapi.dev/api/v1/
    vars:
      my_var: "one"
      another_var: "two"
    headers:
      Content-Type: application/json
    requests:
      - name: nioh
        path: nioh/?${my_var}&${another_var}
      - name: eldenring
        path: eldenring/?${my_var}&${another_var}
        vars:
          my_var: "three"
          another_var: "four"
      - name: darksouls
        path: darksouls/?${my_var}&${another_var}
```

Currently, it would result in:

```js
Making request GET http://demo.scanapi.dev/api/v1/nioh/?one&two
Making request GET http://demo.scanapi.dev/api/v1/eldenring/?one&two
Making request GET http://demo.scanapi.dev/api/v1/darksouls/?three&four
```

Which I think it's not the right output because when requesting the ```/eldenring``` endpoint we already have the same variables declared in that scope, then the right behaviour would be adopting  appending ```/three&four``` in the URL.

I made some changes on ```request_node.py``` in order to fix our main problem that is not being able to declare and use variables in the request scope.

These changes were:

```python
def __init__(self, spec, endpoint):
        self.spec = spec
        self.endpoint = endpoint
        # Adds EndpointNode as RequestNode parent
        self.parent = endpoint
        self._validate()
        # Adds SpecEvaluator in order to evaluate variables in this scope
        self.spec_vars = SpecEvaluator(self, spec.get(VARS_KEY, {}))
```

```python
 @property
    def full_url_path(self):
        base_path = self.endpoint.path
        path = str(self.spec.get(PATH_KEY, ""))
        full_url = join_urls(base_path, path)

        # This is not the final code, I'll find a better way to write this 
        # but this fixes our problem of not being able to use variables in request scope.
        # First we evaluate all variables in the EndpointNode
        # then we evaluate again with variables of RequestNode 
        evaluated_url = self.endpoint.spec_vars.evaluate(full_url)
        evaluated_url = self.spec_vars.evaluate(full_url)     

        return evaluated_url
```
Which results in:

```js
Making request GET http://demo.scanapi.dev/api/v1/nioh/?one&two
Making request GET http://demo.scanapi.dev/api/v1/eldenring/?three&four
Making request GET http://demo.scanapi.dev/api/v1/darksouls/?three&four
```

Here you can see that the ```/darksouls``` adopted the same variable values as declared in ```/eldenring```

Is that something expected? 

OBS: Sorry for the giant text 😆
