### ISSUE TITLE
Using comprehensions in assert statements causes a NameError

### ISSUE THREAD

**Issue by shifqu** [scanapi/scanapi#512]
### Environment
- Operating System: MacOS 11.5.2 (Also tested on Win10)
- Python version: 3.9.6 (Also tested with 3.7.11)

### Description of the bug 
Whenever you use a comprehension in the code that is passed to `CodeEvaluator._assert_code`, a NameError will be raised (`NameError: name 'response' is not defined`).

### Expected behavior ?
It would be expected that the eval command does not raise the NameError, but properly evaluates the `code`.

### How to reproduce the the bug ?
```yaml
endpoints:
  - name: httpbin
    path: https://httpbin.org
    headers:
      Accept: application/json
    endpoints:
      - name: http-methods
        requests:
          - name: post-simple
            path: /post
            method: post
            vars:
              scanapi_var: scanapi_test1
              expected_body_keys: "description,scanapi_test"
            body:
              description: hello scanapi
              scanapi_test: ${scanapi_var}
            tests:
              - name: body_contains_expected_body_keys
                assert: ${{ all(key in response.json()["json"] for key in "${expected_body_keys}".split(",")) }}
```

### Anthing else we need to know?
ScanAPI treats this as an Error in the report. ![See this screenshot](https://user-images.githubusercontent.com/28918820/134510288-73e5102e-b9b8-40b3-9cb2-9921e559ac98.png)

I did some digging and fear that this is due to the fact that a comprehension will have its own local context, and the response is only passed in the `locals` from the method `_assert_code`.

### Current workaround
By modifying the `eval` call to add the `response` to the globals ([2nd parameter in eval](https://docs.python.org/3/library/functions.html#eval)), the above yaml definition would correctly evaluate.

I changed the eval statement to:
`eval(code, {**globals(), **{"response": response}})`
I included the current globals, so that even in comprehensions, we have access to the few modules ScanAPI provides by default.

This workaround (mutating the globals context of the eval commands) got me thinking about dynamically being able to import some custom or third-party module or method, which would then be available in an eval statement. It feels like that change would be smaller than the current change discussed in https://github.com/scanapi/scanapi/pull/324
