### ISSUE TITLE
How do I pass a POST request using Content-Type: application / x-www-form-urlencoded

### ISSUE THREAD

**Issue by BrayanMota** [scanapi/scanapi#521]
### Environment
- Operating System: Ubuntu 20.04.3 LTS
- Python version: 3.8.10

### What you intend to do with scanapi ?
Studies
I was trying to implement the scan api with a mini authentication project using FastAPI:

```python
@app.post("/v1/login")
async def login(usuario: OAuth2PasswordRequestForm = Depends()):
    """Método de login usado pelo protocolo de autenticação oauth2_scheme

    Parameters
    ----------
    usuario : OAuth2PasswordRequestForm
        O parâmetro usa a classe do fastapi que gera uma modal de autenticação, fazendo uma verificação de login. O Depends indica que esse parãmetro deve ser
        atendido primeiro para a continuação do método

    Returns
    -------
    JSON
        O retorno trará um dicionário com o token criado ao usuário se autenticar
    """
    
    login = models.Usuario.objects(nome_usuario__exact=usuario.username).first()
    
    if not login:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND ,detail='Usuário inválido')
    
    if not security.verificar_senha(login.senha, usuario.password):
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND ,detail='Senha inválida')
    
    if not login.ativo:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail='Usuário inativo')
    
    expiracao_token_acesso = security.timedelta(minutes=security.ACCESS_TOKEN_EXPIRE_MINUTES)
    token_acesso = security.criar_token_acesso(data={"sub": login.nome_usuario}, expires_delta=expiracao_token_acesso)
    
    return {"token": token_acesso, "token_type": "Bearer"}
```

In this project, to authenticate, I'm using a feature of FastAPI and OAuth2, OAuth2PasswordRequestForm, in it I authenticate to access the dependent endpoints in my project. To make the request, I need to send the body as a Form-Code and not JSON,
and from what I've seen, the form-encode doesn't send the request through the body, so how should I make this request through ScanAPI?

```yaml
endpoints:
  - name: Tributário #Nome do Teste
    path: http://127.0.0.1:8000/v1/ # Caminho Raiz da API
    headers: # Configurando o head da requisição
      Accept: application/json
    requests:
      - name: Autenticação # Criando o Primeiro Request
        path: login # Informando qual o caminho do endpoint, esse será concatenado com o path anterior
        headers:
          Content-Type: application/x-www-form-urlencoded
        method: post # Informando qual o verbo HTTP
        body:
          username: brayan
          password: 123

        vars:
          token: ${{ response.json().get('token') }}
        tests: # Area para os testes
          - name: status_code # Nome do Teste
            assert: ${{ response.status_code == 200 }}
```

### Expected behavior ?
Answer this question.
---

**Comment by viniciusbatistazup** [comment]
.. same problem..

```
endpoints:
  - name: testing
    path: https://keycloak..
    requests:
      - name: token
        path: /auth/token
        headers:
          Content-Type: 'application/x-www-form-urlencoded'
        method: post 
        body:
          grant_type: client_credentials
          client_id: idexample
          client_secret: 71c2-414a-809a-db8ac68cx30b
        tests:
          - name: status_code_is_200 
            assert: ${{ response.status_code == 200 }}
```

My body convert type to **binary** .. i need  **x-www-form-urlencoded'** as explicit in my headers
