### ISSUE TITLE
curl generation doesn't take verify: false into account

### ISSUE THREAD

**Issue by Crocmagnon** [scanapi/scanapi#554]
### Environment
- Operating System: not relevant
- Python version: not relevant

### Description of the bug 
When using `verify: false`, the curl command generated without the `--inscure / -k` flag.

### Expected behavior ?
The generated curl should include `--insecure / -k` when the request is not verified.

### How to reproduce the the bug ?
```yaml
endpoints:
  - name: scanapi-demo
    path: http://demo.scanapi.dev/api/
    options:
        verify: false
    requests:
      - name: list_all_devs
        path: devs/
        method: get
```
then
```
scanapi run
```

Then observe the genreated curl.

### Anthing else we need to know?
curlify2 supports a `verify` argument on the `to_curl` method: https://github.com/marcuxyz/curlify2/blob/fc0fd402f77dea7c8c28840eeaa2886dc287f040/curlify2/curlify.py#L1
