### ISSUE TITLE
Validate mandatory keys for API spec

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#64]
## Description

We need to ensure that API spec has some mandatories keys in order to work properly.

The first mandatory key that need to be checked is the key `api`. The specification should start with it.
https://github.com/scanapi/scanapi/blob/master/scanapi/__init__.py#L68

Under the key `endpoints`, we need to ensure each entry has **at least** a `name` and a `requests` key
https://github.com/scanapi/scanapi/blob/master/scanapi/tree/endpoint_node.py#L79

Under the key `requests`, we need to ensure each entry has **at least** a `name` and a `path` key.
https://github.com/scanapi/scanapi/blob/master/scanapi/tree/request_node.py#L106

This is an example of a minimal possible structure:

```yaml
api:
  endpoints:
    - name: scanapi-demo
      requests:
        - name: health
          path: http://demo.scanapi.dev/api/health/
```

If any of this mandatories keys is missing, an [error](https://github.com/scanapi/scanapi/blob/master/scanapi/errors.py) should be raised.
