### ISSUE TITLE
Adapt Pytest and Codecov workflow to avoid failure on forks

### ISSUE THREAD

**Issue by camilamaia** [scanapi/scanapi#739]
The current [Pytest and Codecov workflow](https://github.com/scanapi/scanapi/blob/main/.github/workflows/pytest-and-codecov.yml) breaks when running in a forked repository.

**Problem:**
When the workflow runs in a fork, it tries to access the `CODECOV_TOKEN` secret, which is not available in forks for security reasons. This causes the workflow to fail.

**Possible solutions:**

* Adjust the workflow to detect when it is running in a fork and skip or modify the Codecov upload step accordingly.
* Use Codecov's built-in support for coverage thresholds (e.g., via `codecov.yml` or action parameters) to enforce minimum coverage and fail the CI if it falls below the limit.

For reference, see the failing run here:
[https://github.com/scanapi/scanapi/actions/runs/15825517892/job/44604576216?pr=725](https://github.com/scanapi/scanapi/actions/runs/15825517892/job/44604576216?pr=725)

**Current relevant workflow snippet:**

```yaml
- name: Upload coverage report to codecov.io
  uses: codecov/codecov-action@v5.4.3
  with:
    token: ${{ secrets.CODECOV_TOKEN }}
    fail_ci_if_error: true
```

**Suggested improvements:**

* Detect if the workflow is running in a fork (e.g., via `github.event.pull_request.head.repo.full_name != github.repository`) and skip Codecov upload or run it without token accordingly.
* Add configuration for coverage threshold enforcement, such as:

  ```yaml
  with:
    fail_ci_if_error: true
    fail_ci_if_error: true
    coverage_threshold: 85 # example percentage
  ```
* Alternatively, use a `codecov.yml` file in the repo to define thresholds, for example:

  ```yaml
  coverage:
    status:
      project:
        default:
          threshold: 85%
          behavior: fail
  ```
